version: '3.7'

services:
    nginx:
        image: reverseproxy:latest
        volumes:
          - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
        ports:
            - 8080:80
        restart: always
    goapp:
        image: goapp:latest
        restart: always
